export const estados = [
    { nome: 'Acre', sigla: 'AC', 'UF': 12 },
    { nome: 'Alagoas', sigla: 'AL', 'UF': 27 },
    { nome: 'Amapá', sigla: 'AP', 'UF': 16 },
    { nome: 'Amazonas', sigla: 'AM', 'UF': 13 },
    { nome: 'Bahia', sigla: 'BA', 'UF': 29 },
    { nome: 'Ceará', sigla: 'CE', 'UF': 23 },
    { nome: 'Distrito Federal', sigla: 'DF', 'UF': 53 },
    { nome: 'Espírito Santo', sigla: 'ES', 'UF': 32 },
    { nome: 'Goiás', sigla: 'GO', 'UF': 52 },
    { nome: 'Maranhão', sigla: 'MA', 'UF': 21 },
    { nome: 'Mato Grosso', sigla: 'MT', 'UF': 51 },
    { nome: 'Mato Grosso do Sul', sigla: 'MS', 'UF': 50 },
    { nome: 'Minas Gerais', sigla: 'MG', 'UF': 31 },
    { nome: 'Pará', sigla: 'PA', 'UF': 15 },
    { nome: 'Paraíba', sigla: 'PB', 'UF': 25 },
    { nome: 'Paraná', sigla: 'PR', 'UF': 41 },
    { nome: 'Pernambuco', sigla: 'PE', 'UF': 26 },
    { nome: 'Piauí', sigla: 'PI', 'UF': 22 },
    { nome: 'Rio de Janeiro', sigla: 'RJ', 'UF': 33 },
    { nome: 'Rio Grande do Norte', sigla: 'RN', 'UF': 24 },
    { nome: 'Rio Grande do Sul', sigla: 'RS', 'UF': 43 },
    { nome: 'Rondônia', sigla: 'RO', 'UF': 11 },
    { nome: 'Roraima', sigla: 'RR', 'UF': 14 },
    { nome: 'Santa Catarina', sigla: 'SC', 'UF': 42 },
    { nome: 'São Paulo', sigla: 'SP', 'UF': 35 },
    { nome: 'Sergipe', sigla: 'SE', 'UF': 28 },
    { nome: 'Tocantins', sigla: 'TO', 'UF': 17 },
  ]